# Generated by Django 5.2.4 on 2025-10-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inner', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.storekeeper'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inner.product'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='inner.product'),
        ),
        migrations.AddField(
            model_name='features',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inner.product'),
        ),
        migrations.AddField(
            model_name='types',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inner.product'),
        ),
        migrations.AddField(
            model_name='typesvalues',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typesvalues_set', to='inner.types'),
        ),
    ]
