# Generated by Django 5.2.4 on 2025-11-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typesvalues',
            name='type',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.DeleteModel(
            name='TypesValues',
        ),
    ]
