# Generated by Django 5.2.4 on 2025-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/%Y/%m/%d'),
        ),
    ]
