# Generated by Django 5.2.4 on 2025-07-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0002_product_amazing_offer_product_amazing_offer_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaskedquestions',
            options={'verbose_name': 'FrequentlyAskedQuestion', 'verbose_name_plural': 'FrequentlyAskedQuestions'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterModelOptions(
            name='typesvalues',
            options={'verbose_name': 'TypesValue', 'verbose_name_plural': 'TypesValues'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterModelTable(
            name='features',
            table='Features',
        ),
        migrations.AlterModelTable(
            name='frequentlyaskedquestions',
            table='FrequentlyAskedQuestions',
        ),
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='types',
            table='Types',
        ),
        migrations.AlterModelTable(
            name='typesvalues',
            table='TypesValues',
        ),
    ]
