# Generated by Django 5.2.4 on 2025-07-31 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0005_alter_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesvalues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typesvalues_set', to='inner.types'),
        ),
    ]
