# Generated by Django 5.2.4 on 2025-08-01 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0006_alter_typesvalues_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storekeeper_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
