# Generated by Django 5.2.4 on 2025-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0007_product_storekeeper_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storekeeper_uuid',
            field=models.UUIDField(),
        ),
    ]
