# Generated by Django 5.2.4 on 2025-08-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0008_alter_product_storekeeper_uuid'),
        ('user', '0004_remove_storekeeper_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storekeeper_uuid',
        ),
        migrations.AddField(
            model_name='product',
            name='storekeeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.storekeeper'),
            preserve_default=False,
        ),
    ]
