# Generated by Django 5.2.4 on 2025-08-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0010_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
