# Generated by Django 5.2.4 on 2025-08-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_productcategory_image'),
        ('inner', '0011_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='categories.productcategory'),
            preserve_default=False,
        ),
    ]
