# Generated by Django 5.2.4 on 2025-08-05 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=999, help_text='موجودی باید بین 0 تا 10000 باشد', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
