# Generated by Django 5.2.4 on 2025-08-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0014_product_stock_quantity_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesvalues',
            old_name='product',
            new_name='type',
        ),
    ]
