# Generated by Django 5.2.4 on 2025-08-15 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        ('inner', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(blank=True, help_text='Enter a rating between 1 and 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inner.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(help_text='The comment this reply relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('user', models.ForeignKey(help_text='The user who answered', on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment_Reply',
                'verbose_name_plural': 'Comment_Replies',
                'db_table': 'Comment_Replies',
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_enabled', models.BooleanField(default=True, help_text='Is chat between buyer and seller enabled?')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='cart.productpayment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inner.product')),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='user.storekeeper')),
            ],
            options={
                'verbose_name': 'Product_Purchase',
                'verbose_name_plural': 'Product_Purchases',
                'db_table': 'Product_Purchases',
                'unique_together': {('buyer', 'product', 'storekeeper')},
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inner.product')),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='user.storekeeper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product_Question',
                'verbose_name_plural': 'Product_Questions',
                'db_table': 'Product_Questions',
            },
        ),
        migrations.CreateModel(
            name='PurchaseChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='comments.productpurchase')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase_Chat',
                'verbose_name_plural': 'Purchase_Chats',
                'db_table': 'Purchase_Chats',
            },
        ),
        migrations.CreateModel(
            name='StoreNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='user.storekeeper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification_Subscription',
                'verbose_name_plural': 'Notification_Subscriptions',
                'db_table': 'Notification_Subscriptions',
                'unique_together': {('user', 'storekeeper')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inner.product')),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.storekeeper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='comments.storenotificationsubscription')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notifications',
            },
        ),
    ]
