# Generated by Django 5.2.4 on 2025-08-31 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_favorite_favoriteitem'),
        ('comments', '0001_initial'),
        ('inner', '0003_alter_images_image'),
        ('user', '0003_alter_storekeeper_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpurchase',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.UniqueConstraint(fields=('buyer', 'product', 'storekeeper', 'payment'), name='unique_purchase_per_payment'),
        ),
    ]
