# Generated by Django 5.2.4 on 2025-10-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        ('comments', '0002_initial'),
        ('inner', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(help_text='The comment this reply relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='user',
            field=models.ForeignKey(help_text='The user who answered', on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inner.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='storekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.storekeeper'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='cart.productpayment'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inner.product'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='storekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='user.storekeeper'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inner.product'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='storekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='user.storekeeper'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasechat',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='comments.productpurchase'),
        ),
        migrations.AddField(
            model_name='purchasechat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storenotificationsubscription',
            name='storekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='user.storekeeper'),
        ),
        migrations.AddField(
            model_name='storenotificationsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='comments.storenotificationsubscription'),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.UniqueConstraint(fields=('buyer', 'product', 'storekeeper', 'payment'), name='unique_purchase_per_payment'),
        ),
        migrations.AlterUniqueTogether(
            name='storenotificationsubscription',
            unique_together={('user', 'storekeeper')},
        ),
    ]
