# Generated by Django 5.2.4 on 2025-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
