# Generated by Django 5.2.4 on 2025-08-05 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_created_at_comment_updated_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(help_text='کامنتی که این پاسخ مربوط به آن است', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('user', models.ForeignKey(help_text='کاربری که پاسخ داده', on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment-Reply',
                'verbose_name_plural': 'Comment-Replies',
                'db_table': 'Comment-Replies',
            },
        ),
    ]
