# Generated by Django 5.2.4 on 2025-10-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
        ('inner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='buyer_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from buyer'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='product_name',
            field=models.TextField(blank=True, help_text='Stores product name in case product is deleted after purchase', null=True),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='storekeeper_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from storekeeper'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='inner.product'),
        ),
    ]
