# Generated by Django 5.2.4 on 2025-08-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_productquestion'),
        ('user', '0005_alter_storekeeper_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='storekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='user.storekeeper'),
        ),
    ]
