# Generated by Django 5.2.4 on 2025-08-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_productquestion_storekeeper'),
        ('inner', '0015_rename_product_typesvalues_type'),
        ('user', '0005_alter_storekeeper_store_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inner.product')),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='user.storekeeper')),
            ],
            options={
                'verbose_name': 'Product-Purchase',
                'verbose_name_plural': 'Product-Purchases',
                'db_table': 'Product-Purchases',
                'unique_together': {('buyer', 'product', 'storekeeper')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='comments.productpurchase')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase-Chat',
                'verbose_name_plural': 'Purchase-Chats',
                'db_table': 'Purchase-Chats',
            },
        ),
    ]
