# Generated by Django 5.2.4 on 2025-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_productpurchase_purchasechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='chat_enabled',
            field=models.BooleanField(default=True, help_text='آیا امکان چت بین خریدار و فروشنده فعال است؟'),
        ),
    ]
