# Generated by Django 5.2.4 on 2025-08-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_productpayment_delivered_at'),
        ('comments', '0008_productpurchase_chat_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='payment',
            field=models.OneToOneField(default=41, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='cart.productpayment'),
            preserve_default=False,
        ),
    ]
