# Generated by Django 5.2.4 on 2025-08-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_storekeeper_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='categories/%Y/%m/%d/')),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user.storekeeper')),
            ],
        ),
    ]
