# Generated by Django 5.2.4 on 2025-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='categories/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
