# Generated by Django 5.2.4 on 2025-08-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_productcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='categories',
        ),
    ]
