# Generated by Django 5.2.4 on 2025-10-15 00:56

import cart.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'db_table': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorite Item',
                'verbose_name_plural': 'Favorite Items',
                'db_table': 'Favorite_Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(editable=False, help_text='Final amount paid for the entire shopping cart')),
                ('fake_card_number', models.CharField(default=cart.models.generate_fake_card_number, max_length=19)),
                ('fake_card_second_password', models.CharField(default=cart.models.generate_fake_second_password, max_length=8)),
                ('fake_card_cvv', models.CharField(default=cart.models.generate_fake_cvv, max_length=4)),
                ('fake_card_expiry', models.CharField(default=cart.models.generate_fake_expiry, max_length=5)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(help_text="Payer's address")),
                ('is_successful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'cart_payment',
                'verbose_name_plural': 'cart_payments',
                'db_table': 'cart_payments',
            },
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True, help_text='Stores product name in case product is deleted after successful payment.', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Paid quantity of the product')),
                ('total_price', models.PositiveIntegerField(editable=False, help_text='Quantity × Unit price of product')),
                ('fake_card_number', models.CharField(default=cart.models.generate_fake_card_number, max_length=19)),
                ('fake_card_second_password', models.CharField(default=cart.models.generate_fake_second_password, max_length=8)),
                ('fake_card_cvv', models.CharField(default=cart.models.generate_fake_cvv, max_length=4)),
                ('fake_card_expiry', models.CharField(default=cart.models.generate_fake_expiry, max_length=5)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(help_text="Payer's address")),
                ('is_successful', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False, help_text='Has the product reached the buyer?')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_hidden', models.BooleanField(default=False, help_text='Hidden from buyer')),
                ('storekeeper_hidden', models.BooleanField(default=False, help_text='Hidden from storekeeper')),
            ],
            options={
                'verbose_name': 'product_payment',
                'verbose_name_plural': 'product_payments',
                'db_table': 'product_payments',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Enter a quantity between 1 and 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Cart_Item',
                'verbose_name_plural': 'Cart_Items',
                'db_table': 'Cart_Items',
            },
        ),
    ]
