# Generated by Django 5.2.4 on 2025-08-02 15:11

import cart.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(editable=False, help_text='مبلغ نهایی پرداخت\u200cشده برای کل سبد خرید')),
                ('fake_card_number', models.CharField(default='1234 5678 9012 3456', max_length=16)),
                ('fake_card_second_password', models.CharField(default=cart.models.generate_fake_second_password, max_length=8)),
                ('fake_card_cvv', models.CharField(default=cart.models.generate_fake_cvv, max_length=4)),
                ('fake_card_expiry', models.CharField(default=cart.models.generate_fake_expiry, max_length=5)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.cart')),
            ],
            options={
                'verbose_name': 'cart_payment',
                'verbose_name_plural': 'cart_payments',
                'db_table': 'cart_payments',
            },
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(editable=False, help_text='تعداد × قیمت واحد محصول')),
                ('fake_card_number', models.CharField(default='1234 5678 9012 3456', max_length=16)),
                ('fake_card_second_password', models.CharField(default=cart.models.generate_fake_second_password, max_length=8)),
                ('fake_card_cvv', models.CharField(default=cart.models.generate_fake_cvv, max_length=4)),
                ('fake_card_expiry', models.CharField(default=cart.models.generate_fake_expiry, max_length=5)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=False)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_payments', to='cart.cartitem')),
            ],
            options={
                'verbose_name': 'product_payment',
                'verbose_name_plural': 'product_payments',
                'db_table': 'product_payments',
            },
        ),
    ]
