# Generated by Django 5.2.4 on 2025-08-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('inner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inner.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='cart',
            field=models.ForeignKey(help_text='The basket to which this partial payment relates.', on_delete=django.db.models.deletion.CASCADE, related_name='product_payments', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='cart.cartitem'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='inner.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_payments',
            field=models.ManyToManyField(blank=True, help_text='List of partial payments related to this overall payment', related_name='main_payment', to='cart.productpayment'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
    ]
