# Generated by Django 5.2.4 on 2025-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='product_name',
            field=models.TextField(blank=True, help_text='Stores product name in case product is deleted after successful payment.', null=True),
        ),
    ]
