# Generated by Django 5.2.4 on 2025-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_payment_fake_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='fake_card_number',
            field=models.CharField(default='1234 5678 9012 3456', max_length=19),
        ),
    ]
