# Generated by Django 5.2.4 on 2025-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_productpayment_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='buyer_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from buyer'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='storekeeper_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from storekeeper'),
        ),
    ]
