# Generated by Django 5.2.4 on 2025-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_favorite_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='end_of_sending',
            field=models.BooleanField(default=False, help_text='Has the sending process been completed?'),
        ),
    ]
