# Generated by Django 5.2.4 on 2025-08-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_productpayment_fake_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(default='ali', help_text='آدرس پرداخت\u200cکننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpayment',
            name='address',
            field=models.TextField(default='ali', help_text='آدرس پرداخت\u200cکننده'),
            preserve_default=False,
        ),
    ]
