# Generated by Django 5.2.4 on 2025-08-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_payment_address_productpayment_address'),
        ('inner', '0012_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_payments',
            field=models.ManyToManyField(blank=True, help_text='لیست پرداخت\u200cهای جزئی مربوط به این پرداخت کلی', related_name='main_payment', to='cart.productpayment'),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='product',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, related_name='product_payments', to='inner.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpayment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='تعداد پرداخت\u200cشده از محصول'),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='cart.cartitem'),
        ),
    ]
