# Generated by Django 5.2.4 on 2025-08-03 10:06

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_payment_product_payments_productpayment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fake_card_number',
            field=models.CharField(default=cart.models.generate_fake_card_number, max_length=19),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='fake_card_number',
            field=models.CharField(default=cart.models.generate_fake_card_number, max_length=19),
        ),
    ]
