# Generated by Django 5.2.4 on 2025-08-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_user_cartitem_unique_product_per_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='cart',
            field=models.ForeignKey(default=1, help_text='سبدی که این پرداخت جزئی مربوط به آن است', on_delete=django.db.models.deletion.CASCADE, related_name='product_payments', to='cart.cart'),
            preserve_default=False,
        ),
    ]
