# Generated by Django 5.2.4 on 2025-08-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_productpayment_cart'),
        ('inner', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='cart.cartitem'),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='inner.product'),
        ),
    ]
