# Generated by Django 5.2.4 on 2025-08-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_productpayment_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='cart.cartitem'),
        ),
    ]
