# Generated by Django 5.2.4 on 2025-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_productpayment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='is_delivered',
            field=models.BooleanField(default=False, help_text='آیا محصول به دست خریدار رسیده است؟'),
        ),
    ]
