# Generated by Django 5.2.4 on 2025-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_productpayment_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
