# Generated by Django 5.2.4 on 2025-10-15 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, help_text='Was the product shipped by the seller?')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Product delivery time (if applicable)', null=True)),
                ('note', models.TextField(blank=True, help_text='Optional seller description about shipping', null=True)),
                ('storekeeper_hidden', models.BooleanField(default=False, help_text='Hidden from storekeeper')),
                ('payment', models.OneToOneField(help_text='Payment with a registered sending status', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='cart.productpayment')),
            ],
            options={
                'verbose_name': 'Product_Delivery_Status',
                'verbose_name_plural': 'Product_Delivery_Statuses',
                'db_table': 'product_delivery_status',
            },
        ),
        migrations.CreateModel(
            name='StoreKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='storekeepers/%Y/%m/%d')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store_Keeper',
                'verbose_name_plural': 'Store_Keepers',
                'db_table': 'Store_Keepers',
            },
        ),
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User UUID',
                'verbose_name_plural': 'User UUIDs',
                'db_table': 'user_uuids',
            },
        ),
    ]
