# Generated by Django 5.2.4 on 2025-08-15 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, help_text='Was the product shipped by the seller?')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Product delivery time (if applicable)', null=True)),
                ('note', models.TextField(blank=True, help_text='Optional seller description about shipping', null=True)),
                ('payment', models.OneToOneField(help_text='Payment with a registered sending status', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='cart.productpayment')),
            ],
            options={
                'verbose_name': 'Product_Delivery_Status',
                'verbose_name_plural': 'Product_Delivery_Statuses',
                'db_table': 'product_delivery_status',
            },
        ),
        migrations.CreateModel(
            name='StoreKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='storekeepers/%Y/%m/%d')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store_Keeper',
                'verbose_name_plural': 'Store_Keepers',
                'db_table': 'Store_Keepers',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='StoreImages/%Y/%m/%d')),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.storekeeper')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'Store_Images',
            },
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequently_asked_question', models.TextField()),
                ('frequently_asked_question_answer', models.TextField()),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='user.storekeeper')),
            ],
            options={
                'verbose_name': 'Frequently_Asked_Question',
                'verbose_name_plural': 'Frequently_Asked_Questions',
                'db_table': 'Store_Frequently_Asked_Questions',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.TextField()),
                ('feature_value', models.TextField()),
                ('storekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='user.storekeeper')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'Store_Features',
            },
        ),
    ]
