# Generated by Django 5.2.4 on 2025-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentlyaskedquestions',
            name='storekeeper',
        ),
        migrations.RemoveField(
            model_name='images',
            name='storekeeper',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='FrequentlyAskedQuestions',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
