# Generated by Django 5.2.4 on 2025-07-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='product',
            new_name='storekeeper',
        ),
        migrations.RenameField(
            model_name='frequentlyaskedquestions',
            old_name='product',
            new_name='storekeeper',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='storekeeper',
        ),
    ]
