# Generated by Django 5.2.4 on 2025-08-01 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_product_features_storekeeper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storekeeper',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
