# Generated by Django 5.2.4 on 2025-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_frequentlyaskedquestions_storekeeper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storekeeper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storekeepers/%Y/%m/%d'),
        ),
    ]
