# Generated by Django 5.2.4 on 2025-10-02 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User UUID',
                'verbose_name_plural': 'User UUIDs',
                'db_table': 'user_uuids',
            },
        ),
    ]
