# Generated by Django 5.2.4 on 2025-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useruuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdeliverystatus',
            name='storekeeper_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from storekeeper'),
        ),
    ]
