# Generated by Django 5.2.4 on 2025-08-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_storekeeper_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storekeeper',
            name='uuid',
        ),
    ]
