# Generated by Django 5.2.4 on 2025-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_storekeeper_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storekeeper',
            name='store_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
