# Generated by Django 5.2.4 on 2025-08-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_productpayment_is_delivered'),
        ('user', '0005_alter_storekeeper_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, help_text='آیا محصول توسط فروشنده ارسال شده است؟')),
                ('sent_at', models.DateTimeField(blank=True, help_text='زمان ارسال محصول (در صورت وجود)', null=True)),
                ('note', models.TextField(blank=True, help_text='توضیحات اختیاری فروشنده درباره ارسال', null=True)),
                ('payment', models.OneToOneField(help_text='پرداختی که وضعیت ارسال آن ثبت شده', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='cart.productpayment')),
            ],
            options={
                'verbose_name': 'Product_Delivery_Status',
                'verbose_name_plural': 'Product_Delivery_Statuses',
                'db_table': 'product_delivery_status',
            },
        ),
    ]
